color: yes
import:
  move: yes
  write: yes
log: ~/.config/beets/import.log
paths:
  default: $albumartist/$album%aunique{}/%if{$disc,$disc -}$track. $artist $title
  singleton: Non-Album/$artist/$artist - $title
  comp: Compilations/$album%aunique{}/$track. $artist - $title

plugins:
  - mpdupdate

mpd:
  host: localhost
  port: 6600
